# Generated by Django 4.2.7 on 2026-04-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(blank=True, max_length=120, verbose_name='Nome da empresa')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('cnpj', models.CharField(blank=True, max_length=30, verbose_name='CNPJ')),
                ('site', models.CharField(blank=True, max_length=120, verbose_name='Site')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sistema/', verbose_name='Logomarca')),
                ('cor_primaria', models.CharField(default='#2563EB', max_length=7, verbose_name='Cor primária (hex)')),
                ('cor_rodape', models.CharField(default='#111827', max_length=7, verbose_name='Cor do rodapé (hex)')),
                ('texto_rodape', models.CharField(blank=True, max_length=200, verbose_name='Texto do rodapé')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
