# Generated by Django 4.2.7 on 2026-03-31 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número')),
                ('data_abertura', models.DateField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_previsao_entrega', models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('aguardando_peca', 'Aguardando Peça'), ('concluida', 'Concluída'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='clientes.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('orcamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ordem_servico', to='orcamentos.orcamento', verbose_name='Orçamento')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OrdemEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Etapa')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('sequencia', models.IntegerField(help_text='Ordem de execução da etapa no processo', verbose_name='Sequência')),
                ('valor_servico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Serviço')),
                ('data_programada', models.DateField(blank=True, null=True, verbose_name='Data Programada')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('aguardando_peca', 'Aguardando Peça')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('percentual_comissao', models.DecimalField(blank=True, decimal_places=2, help_text='Se não definido, usa o percentual padrão do funcionário', max_digits=5, null=True, verbose_name='Percentual de Comissão (%)')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etapas_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='ordens.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Etapa da Ordem',
                'verbose_name_plural': 'Etapas das Ordens',
                'ordering': ['ordem', 'sequencia'],
                'unique_together': {('ordem', 'sequencia')},
            },
        ),
    ]
