# Generated by Django 4.2.7 on 2026-04-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0002_alter_ordemetapa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemetapa',
            name='status',
            field=models.CharField(choices=[('patio', 'No Pátio'), ('aguardando_liberacao', 'Aguardando Liberação'), ('liberado', 'Liberado'), ('aguardando_programacao', 'Aguardando Programação'), ('programado', 'Programado'), ('em_servico', 'Em Serviço'), ('aguardando_peca', 'Aguardando Peça'), ('parado', 'Parado'), ('concluido', 'Concluído')], default='aguardando_liberacao', max_length=30, verbose_name='Status'),
        ),
    ]
