# Generated by Django 4.2.7 on 2026-04-06 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordens', '0003_alter_ordemetapa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemetapa',
            name='auxiliares',
            field=models.ManyToManyField(blank=True, related_name='etapas_como_auxiliar', to=settings.AUTH_USER_MODEL, verbose_name='Auxiliares'),
        ),
        migrations.AddField(
            model_name='ordemetapa',
            name='horas_gastas_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Horas Realizadas'),
        ),
        migrations.AddField(
            model_name='ordemetapa',
            name='horas_orcadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Horas Orçadas'),
        ),
        migrations.AlterField(
            model_name='ordemetapa',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etapas_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='ordemetapa',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('programado', 'Programado'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('aguardando_peca', 'Aguardando Peça')], default='aguardando', max_length=30, verbose_name='Status'),
        ),
    ]
