# Generated by Django 4.2.7 on 2026-04-06 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordens', '0004_ordemetapa_auxiliares_ordemetapa_horas_gastas_real_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True, verbose_name='Início')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('duracao_minutos', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Duração (minutos)')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='ordens.ordemetapa', verbose_name='Etapa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_trabalho', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Sessão de Trabalho',
                'verbose_name_plural': 'Sessões de Trabalho',
                'ordering': ['-inicio'],
            },
        ),
    ]
