# Generated by Django 4.2.7 on 2026-04-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0005_sessaotrabalho'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_chegada_veiculo',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Chegada do Veículo'),
        ),
    ]
