# Generated by Django 4.2.7 on 2026-04-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0006_ordemservico_data_chegada_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemetapa',
            name='permitir_horas_extras',
            field=models.BooleanField(default=False, verbose_name='Permitir Horas Extras'),
        ),
    ]
