# Generated by Django 4.2.7 on 2026-04-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ordens', '0007_ordemetapa_permitir_horas_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemetapa',
            name='execucao',
            field=models.CharField(
                choices=[('oficina', 'Oficina'), ('terceiro', 'Terceiro')],
                default='oficina',
                max_length=10,
                verbose_name='Execução',
            ),
        ),
    ]

