# Generated by Django 4.2.7 on 2026-03-31 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True, verbose_name='Ano de Fabricação')),
                ('ano_modelo', models.IntegerField(blank=True, null=True, verbose_name='Ano do Modelo')),
                ('cor', models.CharField(blank=True, max_length=30, verbose_name='Cor')),
                ('chassi', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Chassi')),
                ('renavam', models.CharField(blank=True, max_length=20, verbose_name='Renavam')),
                ('km_atual', models.IntegerField(blank=True, null=True, verbose_name='KM Atual')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
            },
        ),
    ]
