# Generated by Django 4.2.7 on 2026-04-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('pais_origem', models.CharField(blank=True, max_length=50, verbose_name='País de Origem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(blank=True, max_length=50, verbose_name='Marca (legado)'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Modelo (legado)'),
        ),
        migrations.CreateModel(
            name='ModeloVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Modelo')),
                ('categoria', models.CharField(choices=[('hatch', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('pickup', 'Picape'), ('van', 'Van/Utilitário'), ('esportivo', 'Esportivo'), ('caminhao', 'Caminhão'), ('moto', 'Motocicleta'), ('outro', 'Outro')], default='sedan', max_length=20, verbose_name='Categoria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='veiculos.fabricante', verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Modelo de Veículo',
                'verbose_name_plural': 'Modelos de Veículos',
                'ordering': ['fabricante__nome', 'nome'],
                'unique_together': {('fabricante', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo_veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='veiculos.modeloveiculo', verbose_name='Modelo'),
        ),
    ]
