# Generated by Django 4.2.7 on 2026-04-04 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_fabricante_alter_veiculo_marca_alter_veiculo_modelo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Cor')),
                ('codigo_hex', models.CharField(blank=True, help_text='Ex: #FFFFFF', max_length=7, verbose_name='Código Hex')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cor de Veículo',
                'verbose_name_plural': 'Cores de Veículos',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(blank=True, max_length=30, verbose_name='Cor (legado)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor_veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='veiculos.corveiculo', verbose_name='Cor'),
        ),
    ]
