# Generated by Django 4.2.7 on 2026-04-04 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_corveiculo_alter_veiculo_cor_veiculo_cor_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator(message='A placa deve seguir o padrão AAA1234 ou ABC1D23 (7 caracteres).', regex='^[A-Z]{3}[0-9][0-9A-Z][0-9]{2}$')], verbose_name='Placa'),
        ),
    ]
