# Generated by Django 4.2.7 on 2026-04-04 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_alter_veiculo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator(message='A placa deve ter exatamente 7 caracteres alfanuméricos.', regex='^[A-Z0-9]{7}$')], verbose_name='Placa'),
        ),
    ]
