# Generated by Django 4.2.7 on 2026-04-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0005_alter_veiculo_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='foto_2',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/fotos/', verbose_name='Foto 2'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='foto_3',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/fotos/', verbose_name='Foto 3'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='foto_4',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/fotos/', verbose_name='Foto 4'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='foto_principal',
            field=models.ImageField(blank=True, help_text='Foto principal do veículo (frente, lateral, etc.)', null=True, upload_to='veiculos/fotos/', verbose_name='Foto Principal'),
        ),
    ]
