# Generated by Django 4.2.7 on 2026-04-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_funcionario_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='funcionarios/fotos/', verbose_name='Foto'),
        ),
    ]
