# Generated by Django 4.2.7 on 2026-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='deve_mudar_senha',
            field=models.BooleanField(default=True, verbose_name='Deve Mudar Senha'),
        ),
    ]