# Generated by Django 4.2.7 on 2026-04-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_logacesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='perfil',
            field=models.CharField(choices=[('operacional', 'Operacional'), ('visual', 'Visual'), ('supervisor', 'Supervisor'), ('gerente', 'Gerente'), ('admin', 'Administrador'), ('orcamentista', 'Orçamentista'), ('financeiro', 'Financeiro')], default='operacional', max_length=20, verbose_name='Perfil'),
        ),
    ]
