# Generated by Django 4.2.7 on 2026-03-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('sequencia', models.IntegerField(unique=True, verbose_name='Sequência')),
                ('cor', models.CharField(default='#3B82F6', max_length=7, verbose_name='Cor (hex)')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('gera_comissao', models.BooleanField(default=True, help_text='Define se etapas deste tipo geram comissão ao serem concluídas', verbose_name='Gera Comissão')),
                ('percentual_comissao_padrao', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual padrão para esta etapa', max_digits=5, null=True, verbose_name='Percentual de Comissão Padrão (%)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Etapa Padrão',
                'verbose_name_plural': 'Etapas Padrão',
                'ordering': ['sequencia'],
            },
        ),
    ]
