# Generated by Django 4.2.7 on 2026-04-25 00:00

from django.db import migrations


def forwards(apps, schema_editor):
    EtapaPadrao = apps.get_model('producao', 'EtapaPadrao')

    EtapaPadrao.objects.filter(nome='Finalizado').update(sequencia=10, cor='#22C55E', ativa=True)
    EtapaPadrao.objects.filter(nome='Preparação Entrega').update(sequencia=9, cor='#14B8A6', ativa=True)

    EtapaPadrao.objects.update_or_create(
        nome='Mecânica',
        defaults={
            'sequencia': 8,
            'cor': '#0EA5E9',
            'ativa': True,
            'gera_comissao': True,
        },
    )

    padroes = [
        ('Pátio', 1, '#6B7280'),
        ('Desmontagem', 2, '#EF4444'),
        ('Funilaria', 3, '#F59E0B'),
        ('Preparação Pintura', 4, '#10B981'),
        ('Pintura', 5, '#3B82F6'),
        ('Montagem', 6, '#8B5CF6'),
        ('Polimento', 7, '#EC4899'),
        ('Preparação Entrega', 9, '#14B8A6'),
        ('Finalizado', 10, '#22C55E'),
    ]
    for nome, sequencia, cor in padroes:
        EtapaPadrao.objects.update_or_create(
            nome=nome,
            defaults={
                'sequencia': sequencia,
                'cor': cor,
                'ativa': True,
            },
        )


def backwards(apps, schema_editor):
    EtapaPadrao = apps.get_model('producao', 'EtapaPadrao')
    EtapaPadrao.objects.filter(nome='Mecânica').delete()
    EtapaPadrao.objects.filter(nome='Preparação Entrega').update(sequencia=8)
    EtapaPadrao.objects.filter(nome='Finalizado').update(sequencia=9)


class Migration(migrations.Migration):
    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

