# Generated by Django 4.2.7 on 2026-03-31 19:30

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('fornecedor_tipo', models.CharField(choices=[('cliente', 'Cliente'), ('seguradora', 'Seguradora'), ('oficina', 'Oficina')], max_length=15, verbose_name='Tipo de Fornecedor')),
                ('fornecedor_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome do Fornecedor')),
                ('valor_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Custo')),
                ('percentual_lucro', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Usado quando fornecedor = oficina', max_digits=5, verbose_name='Percentual de Lucro (%)')),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automaticamente quando fornecedor = oficina', max_digits=10, null=True, verbose_name='Valor de Venda')),
                ('status', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprovada', 'Aprovada'), ('pedida', 'Pedida'), ('recebida', 'Recebida'), ('cancelada', 'Cancelada')], default='solicitada', max_length=15, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Aprovação')),
                ('data_pedido', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pedido')),
                ('data_previsao', models.DateField(blank=True, null=True, verbose_name='Previsão de Chegada')),
                ('data_recebimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('etapa_bloqueada', models.ForeignKey(blank=True, help_text='Etapa que está aguardando esta peça', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas_bloqueantes', to='ordens.ordemetapa', verbose_name='Etapa Bloqueada')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='ordens.ordemservico', verbose_name='Ordem de Serviço')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pecas_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
                'ordering': ['-criado_em'],
            },
        ),
    ]
