# Generated by Django 4.2.7 on 2026-04-04 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0005_alter_veiculo_placa'),
        ('ordens', '0003_alter_ordemetapa_status'),
        ('pecas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peca',
            name='data_previsao',
        ),
        migrations.AddField(
            model_name='peca',
            name='data_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Data Efetiva da Compra'),
        ),
        migrations.AddField(
            model_name='peca',
            name='prazo_chegada',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo para Chegada'),
        ),
        migrations.AddField(
            model_name='peca',
            name='prazo_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo para Compra'),
        ),
        migrations.AddField(
            model_name='peca',
            name='veiculo',
            field=models.ForeignKey(blank=True, help_text='Vincule esta peça a um veículo específico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas', to='veiculos.veiculo', verbose_name='Veículo'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='ordem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='ordens.ordemservico', verbose_name='Ordem de Serviço'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='status',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('aprovada', 'Aprovada'), ('comprada', 'Comprada'), ('em_transito', 'Em Trânsito'), ('recebida', 'Recebida'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=15, verbose_name='Status'),
        ),
    ]
