# Generated by Django 4.2.7 on 2026-04-04 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
        ('pecas', '0002_remove_peca_data_previsao_peca_data_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas', to='orcamentos.orcamento', verbose_name='Orçamento'),
        ),
    ]
