# Generated by Django 4.2.7 on 2026-04-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0003_peca_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='status',
            field=models.CharField(choices=[('falta_comprar', 'Falta Comprar'), ('comprada', 'Peça Comprada'), ('atrasada', 'Peça Atrasada'), ('recebida', 'Recebida'), ('cancelada', 'Cancelada')], default='solicitada', max_length=15, verbose_name='Status'),
        ),
    ]
