# Generated by Django 4.2.7 on 2026-04-04 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('pecas', '0004_alter_peca_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text='Selecione o fornecedor cadastrado no sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas_fornecidas', to='clientes.cliente', verbose_name='Fornecedor (Cliente)'),
        ),
    ]
