# Generated by Django 4.2.7 on 2026-04-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0005_peca_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='fornecedor_tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('seguradora', 'Seguradora'), ('escritorio', 'Escritório')], max_length=15, verbose_name='Tipo de Fornecedor'),
        ),
    ]
