# Generated by Django 4.2.7 on 2026-04-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0006_alter_peca_fornecedor_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, unique=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Catálogo de Peça',
                'verbose_name_plural': 'Catálogo de Peças',
                'ordering': ['descricao'],
            },
        ),
    ]
