# Generated by Django 4.2.7 on 2026-04-16

from django.db import migrations


def popular_catalogo_pecas(apps, schema_editor):
    Peca = apps.get_model('pecas', 'Peca')
    CatalogoPeca = apps.get_model('pecas', 'CatalogoPeca')

    descricoes = (
        Peca.objects.exclude(descricao__isnull=True)
        .exclude(descricao__exact='')
        .values_list('descricao', flat=True)
        .distinct()
    )

    for d in descricoes:
        desc = (d or '').strip()
        if not desc:
            continue
        CatalogoPeca.objects.get_or_create(descricao=desc, defaults={'ativo': True})


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0007_catalogopeca'),
    ]

    operations = [
        migrations.RunPython(popular_catalogo_pecas, migrations.RunPython.noop),
    ]

