# Generated by Django 4.2.7 on 2026-04-16

from decimal import Decimal
from django.db import migrations, models


def preencher_padrao_do_catalogo(apps, schema_editor):
    CatalogoPeca = apps.get_model('pecas', 'CatalogoPeca')
    Peca = apps.get_model('pecas', 'Peca')

    for item in CatalogoPeca.objects.all():
        p = (
            Peca.objects.filter(descricao=item.descricao)
            .order_by('-criado_em', '-id')
            .first()
        )
        if not p:
            continue

        try:
            item.fornecedor_tipo = p.fornecedor_tipo or item.fornecedor_tipo
        except Exception:
            pass
        try:
            item.quantidade = p.quantidade or item.quantidade or 1
        except Exception:
            item.quantidade = item.quantidade or 1
        try:
            item.valor_custo = p.valor_custo
        except Exception:
            pass
        try:
            item.percentual_lucro = p.percentual_lucro or item.percentual_lucro or Decimal('30.00')
        except Exception:
            item.percentual_lucro = item.percentual_lucro or Decimal('30.00')

        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0008_popular_catalogopeca'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogopeca',
            name='fornecedor_tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('seguradora', 'Seguradora'), ('escritorio', 'Escritório')], default='escritorio', max_length=15, verbose_name='Fornecedor padrão'),
        ),
        migrations.AddField(
            model_name='catalogopeca',
            name='percentual_lucro',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='Lucro padrão (%)'),
        ),
        migrations.AddField(
            model_name='catalogopeca',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Quantidade padrão'),
        ),
        migrations.AddField(
            model_name='catalogopeca',
            name='valor_custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo padrão'),
        ),
        migrations.RunPython(preencher_padrao_do_catalogo, migrations.RunPython.noop),
    ]

