# Generated by Django 4.2.7 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0009_catalogopeca_campos_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='status',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('falta_comprar', 'Falta Comprar'), ('comprada', 'Peça Comprada'), ('atrasada', 'Peça Atrasada'), ('recebida', 'Recebida'), ('cancelada', 'Cancelada')], default='falta_comprar', max_length=15, verbose_name='Status'),
        ),
    ]

