# Generated by Django 4.2.7 on 2026-04-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0009_orcamentoaditivo'),
        ('pecas', '0010_alter_peca_status_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='aditivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pecas', to='orcamentos.orcamentoaditivo', verbose_name='Aditivo'),
        ),
    ]

