# Generated by Django 4.2.7 on 2026-04-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='atividade_fornecedor',
            field=models.CharField(blank=True, help_text='Ex: Mecânica, Ar Condicionado, Material de Pintura', max_length=150, verbose_name='Atividade do Fornecedor'),
        ),
    ]
