# Generated by Django 4.2.7 on 2026-04-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_atividade_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='proprietario',
            field=models.CharField(blank=True, max_length=200, verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato_proprietario',
            field=models.CharField(blank=True, max_length=30, verbose_name='Contato do Proprietário'),
        ),
    ]

