# Generated by Django 4.2.7 on 2026-03-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_servico', models.DecimalField(decimal_places=2, help_text='Valor da etapa no momento da geração', max_digits=10, verbose_name='Valor do Serviço')),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Percentual usado no cálculo', max_digits=5, verbose_name='Percentual (%)')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Calculado: valor_servico * percentual / 100', max_digits=10, verbose_name='Valor da Comissão')),
                ('tempo_execucao_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tempo de Execução (horas)')),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=15, verbose_name='Status do Pagamento')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
                'ordering': ['-criado_em'],
            },
        ),
    ]
