# Generated by Django 4.2.7 on 2026-03-31 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordens', '0001_initial'),
        ('comissoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comissoes_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='comissao',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comissoes', to='ordens.ordemetapa', verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='comissao',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comissoes', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='comissao',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comissoes', to='ordens.ordemservico', verbose_name='Ordem de Serviço'),
        ),
    ]
