# Generated by Django 4.2.7 on 2026-04-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='data_execucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Execução'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Em aberto'), ('aprovada', 'Aprovada'), ('paga', 'Pago'), ('cancelada', 'Cancelada')], default='pendente', max_length=15, verbose_name='Status do Pagamento'),
        ),
        migrations.AddConstraint(
            model_name='comissao',
            constraint=models.UniqueConstraint(fields=('etapa', 'funcionario'), name='uniq_comissao_etapa_funcionario'),
        ),
    ]
