# Generated by Django 4.2.7 on 2026-04-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Etapa')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição Padrão')),
                ('ordem_default', models.IntegerField(default=0, help_text='Ex: 10, 20, 30 (impacta na ordenação)', verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Etapa Padrão',
                'verbose_name_plural': 'Etapas Padrões',
                'ordering': ['ordem_default', 'nome'],
            },
        ),
        migrations.RemoveField(
            model_name='orcamentoitem',
            name='etapa_nome',
        ),
        migrations.AddField(
            model_name='orcamentoitem',
            name='etapa',
            field=models.ForeignKey(help_text='Etapa padronizada (ex: Funilaria, Pintura)', null=True, on_delete=django.db.models.deletion.PROTECT, to='orcamentos.etapapadrao', verbose_name='Etapa'),
        ),
    ]
