# Generated by Django 4.2.7 on 2026-04-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_etapapadrao_remove_orcamentoitem_etapa_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoitem',
            name='horas_previstas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tempo estimado da atividade em horas', max_digits=5, verbose_name='Horas Previstas'),
        ),
    ]
