# Generated by Django 4.2.7 on 2026-04-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_atividade_fornecedor'),
        ('orcamentos', '0003_orcamentoitem_horas_previstas'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoServicoTerceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição do Serviço/Peça')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('fornecedor', models.ForeignKey(limit_choices_to={'categoria__in': ['fornecedor', 'ambos']}, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Fornecedor / Especialista')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_terceiros', to='orcamentos.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Serviço Terceirizado de Orçamento',
                'verbose_name_plural': 'Serviços Terceirizados de Orçamentos',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
    ]
