# Generated by Django 4.2.7 on 2026-04-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0004_orcamentoservicoterceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoitem',
            name='retrabalho',
            field=models.BooleanField(default=False, help_text='Marque se for uma etapa de retrabalho (perda/prejuízo sem receita)', verbose_name='Retrabalho'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('retrabalho', 'Retrabalho'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20, verbose_name='Status'),
        ),
    ]
