# Generated by Django 4.2.7 on 2026-04-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0005_orcamentoitem_retrabalho_alter_orcamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='perda_total',
            field=models.BooleanField(default=False, verbose_name='Perda Total'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Aguardando Resposta'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('retrabalho', 'Retrabalho'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20, verbose_name='Status'),
        ),
    ]
