# Generated by Django 4.2.7 on 2026-04-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0006_orcamento_perda_total_alter_orcamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data_agendada',
            field=models.DateField(blank=True, null=True, verbose_name='Agenda (Entrada na Oficina)'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Aguardando Resposta'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('entregue', 'Entregue'), ('retrabalho', 'Retrabalho'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20, verbose_name='Status'),
        ),
    ]
