# Generated by Django 4.2.7 on 2026-04-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0007_orcamento_data_agendada_alter_orcamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data_prevista_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega'),
        ),
    ]
