# Generated by Django 4.2.7 on 2026-04-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orcamentos', '0008_orcamento_data_prevista_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoAditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado ao Cliente'), ('ciente', 'Ciente (Aprovado pelo Cliente)')], default='rascunho', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aditivos_orcamento_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='orcamentos.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Aditivo de Orçamento',
                'verbose_name_plural': 'Aditivos de Orçamento',
                'ordering': ['-criado_em'],
            },
        ),
    ]

