# Generated by Django 4.2.7 on 2026-04-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0009_orcamentoaditivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoRevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo da Revisão')),
                ('snapshot_antes', models.JSONField(verbose_name='Snapshot Antes')),
                ('snapshot_depois', models.JSONField(blank=True, null=True, verbose_name='Snapshot Depois')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('confirmado_em', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisoes_orcamento_criadas', to='funcionarios.funcionario', verbose_name='Criado por')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='orcamentos.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Revisão de Orçamento',
                'verbose_name_plural': 'Revisões de Orçamento',
                'ordering': ['-criado_em'],
            },
        ),
    ]

