# Generated by Django 4.2.7 on 2026-04-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0010_orcamentorevisao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='inativo',
            field=models.BooleanField(default=False, verbose_name='Inativo'),
        ),
    ]

