# Generated by Django 4.2.7 on 2026-04-25 00:00

from django.db import migrations


def forwards(apps, schema_editor):
    EtapaPadrao = apps.get_model('orcamentos', 'EtapaPadrao')
    EtapaPadrao.objects.update_or_create(
        nome='Mecânica',
        defaults={
            'descricao': '',
            'ordem_default': 75,
            'ativo': True,
        },
    )


def backwards(apps, schema_editor):
    EtapaPadrao = apps.get_model('orcamentos', 'EtapaPadrao')
    EtapaPadrao.objects.filter(nome='Mecânica').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('orcamentos', '0011_orcamento_inativo'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

